debug = false
destination = "personalcapital"
priceDataSource = "coinbase"
destinationCurrencyAs = "USD"
onHoldingNotFound = "zeroQuantity"
[holdings]
    [holdings.coinbase]
    apiKey = "your-key"
    apiSecret = "your-secret"
    debug = false
    [holdings.etherscan]
    apiKey = "your-key"
    debug = false
        [[holdings.etherscan.account]]
        address = "your-address"
        symbolName = "ETH"
        fullName = "Ethereum"
        decimals = 18
        [[holdings.etherscan.account]]
        address = "your-address"
        contractAddress = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
        symbolName = "USDC"
        fullName = "USD Coin"
        decimals = 6
    [holdings.coinbasepro]
    debug = true
        [[holdings.coinbasepro.portfolios]]
        name = "default_portfolio"
        secret = "some_secret"
        key = "some_key"
        passphrase = "some_pass_phrase"
        # If base_url is left blank with default to the value below
        base_url = "https://api.pro.coinbase.com"
    [holdings.bscscan]
    apiKey = "some-api-key"
    debug = false
    # If base_url is defaulted to the below url
    # base_url = "https://api.bscscan.com/api?"
        [[holdings.bscscan.account]]
        address = "0xaddress"
        symbolName = "BNB"
        fullName = "Binance Coin"
        decimals = 18
[destinations]
    [destinations.personalcapital]
    email = "example@email.com"
    password = "password"
    accountName = "CryptoSync managed automatically"