debug = false
destination = "personalcapital"
priceDataSource = "coinbase"
destinationCurrencyAs = "USD"
onHoldingNotFound = "zeroQuantity"
[holdings]
    [holdings.coinbase]
    apiKey = "your-key"
    apiSecret = "your-secret"
    debug = false
    [holdings.ether]
    apiKey = "your-key"
    debug = false
        [[holdings.ether.account]]
        address = "your-address"
        symbolName = "ETH"
        fullName = "Ethereum"
        decimals = 18
        [[holdings.ether.account]]
        address = "your-address"
        contractAddress = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
        symbolName = "USDC"
        fullName = "USD Coin"
        decimals = 6
[destinations]
    [destinations.personalcapital]
    email = "example@email.com"
    password = "password"
    accountName = "CryptoSync managed automatically"