debug = false
destination = "personalcapital"
# you may also specify multiple sources seperated by a comma
# this will allow get a value of a token from another provider should the other not provide any data
# make sure to not have spaces between them
# example: nomics,coinbase,coingecko
priceDataSource = "coinbase"
destinationCurrencyAs = "USD"
onHoldingNotFound = "zeroQuantity"
[pricing]
    [pricing.nomics]
    apiKey = "your-key"
    debug = false

    [pricing.coinbase]
    apiKey = "your-key"
    apiSecret = "your-secret"
    debug = false

[symbols]
    [symbols.global]
        [symbols.override]
            [symbols.override.nomics]
            IOTA = "IOT"
            [symbols.override.coingecko]
            Cake = "pancakeswap-token"

[holdings]
    [holdings.coinbase]
    apiKey = "your-key"
    apiSecret = "your-secret"
    debug = false

    [holdings.etherscan]
    apiKey = "your-key"
    debug = false
        [[holdings.etherscan.account]]
        address = "your-address"
        symbolName = "ETH"
        fullName = "Ethereum"
        decimals = 18
        [[holdings.etherscan.account]]
        address = "your-address"
        contractAddress = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
        symbolName = "USDC"
        fullName = "USD Coin"
        decimals = 6

    [holdings.coinbasepro]
    debug = true
        [[holdings.coinbasepro.portfolios]]
        name = "default_portfolio"
        secret = "some_secret"
        key = "some_key"
        passphrase = "some_pass_phrase"
        # If base_url is left blank with default to the value below
        base_url = "https://api.pro.coinbase.com"

    [holdings.bscscan]
    apiKey = "some-api-key"
    debug = false
    # If base_url is defaulted to the below url
    # base_url = "https://api.bscscan.com/api?"
        [[holdings.bscscan.account]]
        address = "0xaddress"
        symbolName = "BNB"
        fullName = "Binance Coin"
        decimals = 18

    [holdings.binance-us]
    debug = false
    apiKey = "some-api-key"
    secret = "some-secret"

    [holdings.binance]
    debug = false
    # Time Window in milliseconds recvWindow for Binance
    recvWindow = 9000
    apiKey = "some-api-key"
    secret = "some-secret"

    [holdings.coinex]
    debug = false
    accessId = "someAccessId"
    secretKey = "someSecretKey"

    [holdings.yieldwatch]
    debug = true
    platforms = ["pancake"]
    walletAddresses = ["0xSomeWalletAddress"]
[destinations]
    [destinations.personalcapital]
    email = "example@email.com"
    password = "password"
    accountName = "CryptoSync managed automatically"