version: '3'

tasks:
  build-coinbase-api:
    cmds:
    - >
      env GO_POST_PROCESS_FILE='gofmt -w' openapi-generator generate -i api/coinbase.yml -o pkg/coinbase
      -g go-experimental -c api/coinbase.config.yaml --enable-post-process-file -t api/templates/coinbase
      --git-repo-id go-crypto-sync --git-user-id will7200
    # remove the go module files, we don't need those
    - rm pkg/coinbase/go.mod && rm pkg/coinbase/go.sum
    silent: false
  build:
    cmds:
    - go build github.com/will7200/go-crypto-sync/cmd/crypto-sync