/*
 * Binance SPOT Public API
 *
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package binance

import (
	"encoding/json"
)

//
// InlineResponse20024AssetDetail struct for InlineResponse20024AssetDetail
type InlineResponse20024AssetDetail struct {
	CTR *InlineResponse20024AssetDetailCTR `json:"CTR,omitempty"`
}

// NewInlineResponse20024AssetDetail instantiates a new InlineResponse20024AssetDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20024AssetDetail() *InlineResponse20024AssetDetail {
	this := InlineResponse20024AssetDetail{}
	return &this
}

// NewInlineResponse20024AssetDetailWithDefaults instantiates a new InlineResponse20024AssetDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20024AssetDetailWithDefaults() *InlineResponse20024AssetDetail {
	this := InlineResponse20024AssetDetail{}
	return &this
}

// GetCTR returns the CTR field value if set, zero value otherwise.
func (o *InlineResponse20024AssetDetail) GetCTR() InlineResponse20024AssetDetailCTR {
	if o == nil || o.CTR == nil {
		var ret InlineResponse20024AssetDetailCTR
		return ret
	}
	return *o.CTR
}

// GetCTROk returns a tuple with the CTR field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20024AssetDetail) GetCTROk() (*InlineResponse20024AssetDetailCTR, bool) {
	if o == nil || o.CTR == nil {
		return nil, false
	}
	return o.CTR, true
}

// HasCTR returns a boolean if a field has been set.
func (o *InlineResponse20024AssetDetail) HasCTR() bool {
	if o != nil && o.CTR != nil {
		return true
	}

	return false
}

// SetCTR gets a reference to the given InlineResponse20024AssetDetailCTR and assigns it to the CTR field.
func (o *InlineResponse20024AssetDetail) SetCTR(v InlineResponse20024AssetDetailCTR) {
	o.CTR = &v
}

func (o InlineResponse20024AssetDetail) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CTR != nil {
		toSerialize["CTR"] = o.CTR
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20024AssetDetail struct {
	value *InlineResponse20024AssetDetail
	isSet bool
}

func (v NullableInlineResponse20024AssetDetail) Get() *InlineResponse20024AssetDetail {
	return v.value
}

func (v *NullableInlineResponse20024AssetDetail) Set(val *InlineResponse20024AssetDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20024AssetDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20024AssetDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20024AssetDetail(val *InlineResponse20024AssetDetail) *NullableInlineResponse20024AssetDetail {
	return &NullableInlineResponse20024AssetDetail{value: val, isSet: true}
}

func (v NullableInlineResponse20024AssetDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20024AssetDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
