packageVersion: 0.1.0
isGoSubmodule: true
packageName: binance
allParams: true
generateInterfaces: true
useOneOfDiscriminatorLookup: true
modulePackageName: pkg/binance
withXml: false
enumClassPrefix: true
topLevelPackageName: github.com/will7200/go-crypto-sync
hideGenerationTimestamp: false
generateAliasAsModel: true