packageVersion: 0.1.0
isGoSubmodule: true
packageName: coinbase
allParams: true
modulePackageName: pkg/coinbase
withXml: false
enumClassPrefix: true
topLevelPackageName: github.com/will7200/go-crypto-sync
hideGenerationTimestamp: false
