packageVersion: 0.1.0
isGoSubmodule: true
packageName: nomics
allParams: true
modulePackageName: pkg/nomics
withXml: false
enumClassPrefix: true
topLevelPackageName: github.com/will7200/go-crypto-sync
hideGenerationTimestamp: false
